version: "3"

services:
  api-server:
    image: oneeonly/r2d2-api-server:latest
    networks: [ testnet ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose: [ "8080" ]
    env_file: .env

  tester:
    image: oneeonly/r2d2-tester:latest
    networks: [ testnet, execnet ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/db/r2d2:/var/db/r2d2
    env_file: .env

  mysql:
    image: mysql:latest
    networks: [ testnet ]
    environment:
      - MYSQL_DATABASE=r2d2
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul

  redis:
    image: redis:latest
    networks: [ testnet ]
    environment:
      - TZ=Asia/Seoul

  influxdb:
    image: influxdb:latest
    networks: [ testnet ]
    expose: [ "8086" ]
    environment:
      - TZ=Asia/Seoul

networks:
  testnet:
    name: test-network
    driver: bridge

  execnet:
    name: exec-network
    driver: bridge
